test: &default

  # Credentials for REST APIs
  client_id: AYds8Bs42CXtrThrSOgGtxPca5DcljQWfsvMrbCGl8TE-sRCJ-LgsOz3YUqsvOO3qubWTBp-JNUY3vdg
  client_secret: EKhIg5qPVxx51xfnOQIRXj6CStp-sxB0aNc3MAlNaD76L600UM5KykbL5164itFbhebNvg0Uc_5iuqPr

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

development:
  <<: *default

production:
  client_id: AUs4Itt0VUMKEeg9t-J_z2cL5JMa6G0xMUgXVeMIIdZL0jivXwUmx_ZaKqGz6I2eeScchdqTxr5ZRdfK
  client_secret: EI11DIedXQ7ycUeAhvLqpD_eJSDHY85NhYCeGKisegU3O7-tBnStBdU_gCopElHEjKV07xiCThGvE4TK
  mode: live
