class CreatePaymentConfirmations < ActiveRecord::Migration
	def change
		create_table :payment_confirmations do |t|
			t.string   "address_city"
			t.string   "address_country"
			t.string   "address_country_code"
			t.string   "address_name"
			t.string   "address_state"
			t.string   "address_status"
			t.string   "address_street"
			t.string   "address_zip"
			t.string   "business"
			t.string   "charset"
			t.string   "custom"
			t.string   "first_name"
			t.string   "last_name"
			t.string  "invoice"
			t.string   "ipn_track_id"
			t.string   "item_name1"
			t.integer  "item_number1"
			t.string   "mc_currency"
			t.float    "mc_fee"
			t.float    "mc_gross_1"
			t.float    "mc_gross"
			t.float    "mc_handling1"
			t.float    "mc_handling"
			t.float    "mc_shipping1"
			t.float    "mc_shipping"
			t.string   "notify_version"
			t.integer  "num_cart_items"
			t.string   "payer_email"
			t.string   "payer_id"
			t.string   "payer_status"
			t.datetime "payment_date"
			t.float    "payment_fee"
			t.float    "payment_gross"
			t.string   "payment_status"
			t.string   "payment_type"
			t.string   "protection_eligibility"
			t.integer  "quantity1"
			t.string   "receiver_email"
			t.string   "receiver_id"
			t.string   "residence_country"
			t.float    "tax"
			t.boolean  "test_ipn"
			t.string   "transaction_subject"
			t.string   "txn_id"
			t.string   "txn_type"
			t.string   "verify_sign"
			t.datetime "created_at"
			t.datetime "updated_at"
			t.integer  "quantity"
			t.string   "pending_reason"
			t.float    "shipping"
			t.string   "item_name"
			t.integer  "item_number"
			t.string   "parent_txn_id"
			t.string   "reason_code"
			t.timestamps
		end
	end
end
